In [ ]:
%%shell
set -e

#---------------------------------------------------#
JULIA_VERSION="1.7.1" # any version ≥ 0.7.0
JULIA_PACKAGES="IJulia CSV DataFrames Random Statistics Distributions LinearAlgebra SparseArrays Printf JWAS"  # CSV DataFrames Random Statistics JWAS Distributions LinearAlgebra
JULIA_PACKAGES_IF_GPU=""
JULIA_NUM_THREADS=4
#---------------------------------------------------#

if [ -n "$COLAB_GPU" ] && [ -z `which julia` ]; then
  # Install Julia
  JULIA_VER=`cut -d '.' -f -2 <<< "$JULIA_VERSION"`
  echo "Installing Julia $JULIA_VERSION on the current Colab Runtime..."
  BASE_URL="https://julialang-s3.julialang.org/bin/linux/x64"
  URL="$BASE_URL/$JULIA_VER/julia-$JULIA_VERSION-linux-x86_64.tar.gz"
  wget -nv $URL -O /tmp/julia.tar.gz # -nv means "not verbose"
  tar -x -f /tmp/julia.tar.gz -C /usr/local --strip-components 1
  rm /tmp/julia.tar.gz

  # Install Packages
  if [ "$COLAB_GPU" = "1" ]; then
      JULIA_PACKAGES="$JULIA_PACKAGES $JULIA_PACKAGES_IF_GPU"
  fi
  for PKG in `echo $JULIA_PACKAGES`; do
    echo "Installing Julia package $PKG..."
    julia -e 'using Pkg; pkg"add '$PKG'; precompile;"' &> /dev/null
  done

  # Install kernel and rename it to "julia"
  echo "Installing IJulia kernel..."
  julia -e 'using IJulia; IJulia.installkernel("julia", env=Dict(
      "JULIA_NUM_THREADS"=>"'"$JULIA_NUM_THREADS"'"))'
  KERNEL_DIR=`julia -e "using IJulia; print(IJulia.kerneldir())"`
  KERNEL_NAME=`ls -d "$KERNEL_DIR"/julia*`
  mv -f $KERNEL_NAME "$KERNEL_DIR"/julia  

  echo ''
  echo "Successfully installed `julia -v`!"
  echo "Please reload this page (press Ctrl+R, ⌘+R, or the F5 key) then"
  echo "jump to the 'Checking the Installation' section."
fi

Installing Julia 1.7.1 on the current Colab Runtime...
2022-08-01 04:12:08 URL:https://storage.googleapis.com/julialang2/bin/linux/x64/1.7/julia-1.7.1-linux-x86_64.tar.gz [123374573/123374573] -> "/tmp/julia.tar.gz" [1]
Installing Julia package IJulia...
Installing Julia package CSV...
Installing Julia package DataFrames...
Installing Julia package Random...
Installing Julia package Statistics...
Installing Julia package JWAS...
Installing IJulia kernel...
[ Info: Installing julia kernelspec in /root/.local/share/jupyter/kernels/julia-1.7

Please reload this page (press Ctrl+R, ⌘+R, or the F5 key) then
jump to the 'Checking the Installation' section.


In [3]:
versioninfo()

Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, haswell)
Environment:
  JULIA_NUM_THREADS = 4


In [4]:
a = 2.5

2.5

In [5]:
5a

12.5

In [6]:
5*a

12.5

In [7]:
ans

12.5

In [8]:
a,b = 1,2

(1, 2)

In [9]:
[a,b]

2-element Vector{Int64}:
 1
 2

In [10]:
a,b = b,a
[a,b]

2-element Vector{Int64}:
 2
 1

In [11]:
1 < a < 3

true

In [12]:
1 < a && a < 3

true

In [13]:
# ternary operator
# res = new variable
# if a == b, then res = a, else res = b
# in this case a == b, so res = a (res = 1)

a = 1
b = 1
c = 2

res = a==b ? a : b

1

In [14]:
# if a == c, then print out a, otherwise print out c
# in this case, a =/= c, so print out c (2)

a == c ? a : c

2

In [15]:
a == c ? 1 : 10

10

In [16]:
a == c-b ? 1 : 10

1

In [17]:
# remainder

99 % 10

9

Arrays

In [18]:
# declaration, initialization, and indexing

# empty vector of double precision floats
# floats = includes decimals
# 64 = take up different computer memory space, different ammount of precision (can be 16, 32, 64 --> larger num = higher precision)
# 1 = array dimension of 1 (vector)
v = Array{Float64,1}()

Float64[]

In [19]:
push!(v,2.0) # push number to vector v

1-element Vector{Float64}:
 2.0

In [20]:
v

1-element Vector{Float64}:
 2.0

In [21]:
push!(v, 3.6)

2-element Vector{Float64}:
 2.0
 3.6

In [22]:
# create vector of size 5

u = Array{Float64,1}(undef, 5) # undef = randomly generated numbers (doesn't matter what the values are, just want to create vector)

5-element Vector{Float64}:
 6.95145450403847e-310
 6.95145450404005e-310
 6.95145450630564e-310
 6.9514545064922e-310
 6.95145450630406e-310

In [23]:
# create matrix of size 3x5
# double precision = way to store values, 64 bits to store
# single precision = 32 bits to store

U = Array{Float64, 2}(undef, 3, 5)

3×5 Matrix{Float64}:
 3.0e-323  1.0e-322   1.5e-322   1.8e-322   2.1e-322
 4.0e-323  1.33e-322  1.6e-322   1.9e-322   2.17e-322
 5.0e-323  1.4e-322   1.63e-322  2.08e-322  2.2e-322

In [24]:
# vector of size 5, of 2.2

u = fill(2.2, 5)

5-element Vector{Float64}:
 2.2
 2.2
 2.2
 2.2
 2.2

In [25]:
# vector with 5 zeros

zeros(5)

5-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [26]:
zeros(3,5)

3×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [27]:
# create zero matrix (same size as U)

zero(U)

3×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [28]:
U

3×5 Matrix{Float64}:
 3.0e-323  1.0e-322   1.5e-322   1.8e-322   2.1e-322
 4.0e-323  1.33e-322  1.6e-322   1.9e-322   2.17e-322
 5.0e-323  1.4e-322   1.63e-322  2.08e-322  2.2e-322

In [29]:
ones(3,5)

3×5 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [30]:
using Random, Statistics, Distributions, LinearAlgebra, DataFrames

In [31]:
# another way to install packages if run into error

#using Pkg
#Pkg.add("Distributions")

In [32]:
Random.seed!(101)

TaskLocalRNG()

In [33]:
rand(3,5) # uniform(0,1) --> uniform distribution from 0 to 1

3×5 Matrix{Float64}:
 0.908852  0.077669  0.654605  0.834604  0.859392
 0.490837  0.936285  0.838255  0.895488  0.939604
 0.648927  0.778036  0.235766  0.51961   0.988397

In [34]:
randn(3,5) # standard normal

3×5 Matrix{Float64}:
  1.92234     0.308766  -0.250012  -0.156213  -0.566148
 -0.0976424  -0.514017   0.868958   1.94966   -1.88439
  0.145262    0.111226   0.361192   1.00426   -0.21067

In [35]:
mean(randn(1_000_000)) # '_' == ',' (1_000_000 == 1,000,000)

-8.252374275052659e-5

In [36]:
var(randn(1_000_000))

0.9996430905257744

In [37]:
Random.seed!(100)

TaskLocalRNG()

In [38]:
M = rand(Binomial(2,0.5),10,20)

10×20 Matrix{Int64}:
 2  1  0  2  0  1  1  0  0  0  0  1  2  2  0  0  2  1  1  0
 0  1  0  0  2  0  1  1  0  1  1  1  2  0  1  0  2  0  1  2
 2  0  1  0  0  0  2  1  2  1  2  0  0  1  0  0  1  1  1  2
 1  1  2  1  0  1  2  2  1  1  1  0  1  2  1  2  2  1  0  1
 2  0  1  2  2  2  1  0  1  2  1  1  1  1  2  2  0  0  0  1
 1  2  1  1  1  1  2  2  1  1  1  1  1  1  1  2  0  1  1  2
 1  1  0  1  0  1  2  1  2  1  0  1  1  2  1  1  1  1  1  0
 1  1  1  2  1  1  1  1  2  0  0  1  0  0  0  1  2  2  2  0
 1  1  1  1  2  0  1  1  2  1  1  1  0  0  1  1  1  1  0  1
 2  1  1  2  1  0  0  0  0  1  2  2  1  1  2  1  1  2  2  1

In [39]:
# [row, column]

M[:,1]

10-element Vector{Int64}:
 2
 0
 2
 1
 2
 1
 1
 1
 1
 2

In [40]:
M[1,:]

20-element Vector{Int64}:
 2
 1
 0
 2
 0
 1
 1
 0
 0
 0
 0
 1
 2
 2
 0
 0
 2
 1
 1
 0

In [41]:
# transposing

M[1,:]'

1×20 adjoint(::Vector{Int64}) with eltype Int64:
 2  1  0  2  0  1  1  0  0  0  0  1  2  2  0  0  2  1  1  0

In [42]:
M[1,:]'M[1,:]

26

In [43]:
M[1,:]'*M[1,:]

26

In [44]:
# dot product (matrix multiplication)

dot(M[1,:],M[1,:])

26

In [45]:
# calcualte dot product manually (square every element and then add)
# '.' = do operation on every element in matrix

M[1,:].^2

20-element Vector{Int64}:
 4
 1
 0
 4
 0
 1
 1
 0
 0
 0
 0
 1
 4
 4
 0
 0
 4
 1
 1
 0

In [46]:
sum(M[1,:].^2)

26

In [47]:
M'M == M'*M

true

In [48]:
# identity matrix

I(3)

3×3 Diagonal{Bool, Vector{Bool}}:
 1  ⋅  ⋅
 ⋅  1  ⋅
 ⋅  ⋅  1

In [49]:
1I(3)

3×3 Diagonal{Int64, Vector{Int64}}:
 1  ⋅  ⋅
 ⋅  1  ⋅
 ⋅  ⋅  1

In [50]:
1.0I(2)

2×2 Diagonal{Float64, Vector{Float64}}:
 1.0   ⋅ 
  ⋅   1.0

In [51]:
A = M'M + I # don't need to specify dimensions for I (will infer same dimension)

20×20 Matrix{Int64}:
 22  10  11  18  10  10  16   9  14  …  12  11  15  12  13  14  14  12  12
 10  12   7  11   8   6  12  10   9      9   9   9   8  10  11  10   9   9
 11   7  11  10   7   6  11   9  10      6   5   8   8  11   9   9   6   9
 18  11  10  21  11  11  13   8  12     13  11  13  12  14  14  14  12   8
 10   8   7  11  16   6   9   7   9     10   8   4  11  10   9   7   7  11
 10   6   6  11   6  10  10   6   8  …   6   7   9   7  10   7   6   5   5
 16  12  11  13   9  10  22  15  17      9  11  15  10  14  15  12  10  14
  9  10   9   8   7   6  15  14  12      6   7   9   7  11  11   9   7  11
 14   9  10  12   9   8  17  12  20      8   5  10   8  12  12  12   9  10
 12   7   8  10  10   7  12   8  10      8   8   9  11  11   8   7   6  11
 13   7   9   9   9   4  11   8   9  …   8   7   8  10   9   9   9   8  13
 12   9   6  13  10   6   9   6   8     12   9   8  10   9  10  10  10   8
 11   9   5  11   8   7  11   7   5      9  14  11   9   8  12   7   8   9
 15 

In [52]:
M'M + I(20) # can specify dimensions for I but don't need to

20×20 Matrix{Int64}:
 22  10  11  18  10  10  16   9  14  …  12  11  15  12  13  14  14  12  12
 10  12   7  11   8   6  12  10   9      9   9   9   8  10  11  10   9   9
 11   7  11  10   7   6  11   9  10      6   5   8   8  11   9   9   6   9
 18  11  10  21  11  11  13   8  12     13  11  13  12  14  14  14  12   8
 10   8   7  11  16   6   9   7   9     10   8   4  11  10   9   7   7  11
 10   6   6  11   6  10  10   6   8  …   6   7   9   7  10   7   6   5   5
 16  12  11  13   9  10  22  15  17      9  11  15  10  14  15  12  10  14
  9  10   9   8   7   6  15  14  12      6   7   9   7  11  11   9   7  11
 14   9  10  12   9   8  17  12  20      8   5  10   8  12  12  12   9  10
 12   7   8  10  10   7  12   8  10      8   8   9  11  11   8   7   6  11
 13   7   9   9   9   4  11   8   9  …   8   7   8  10   9   9   9   8  13
 12   9   6  13  10   6   9   6   8     12   9   8  10   9  10  10  10   8
 11   9   5  11   8   7  11   7   5      9  14  11   9   8  12   7   8   9
 15 

In [53]:
B = rand(3,3) + I

3×3 Matrix{Float64}:
 1.45742     0.905428  0.428537
 0.00450378  1.4083    0.831837
 0.26018     0.940167  1.68669

In [54]:
B*I

3×3 Matrix{Float64}:
 1.45742     0.905428  0.428537
 0.00450378  1.4083    0.831837
 0.26018     0.940167  1.68669

In [55]:
B == B*I

true

In [56]:
B === B*I # triple equality = whether two operations are exactly the same (even if values are the same)

false

In [57]:
Diagonal(A) # all diagonal values of matrix

20×20 Diagonal{Int64, Vector{Int64}}:
 22   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  …   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅  12   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅      ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅  11   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅      ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅  21   ⋅   ⋅   ⋅   ⋅   ⋅      ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅   ⋅  16   ⋅   ⋅   ⋅   ⋅      ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅  10   ⋅   ⋅   ⋅  …   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  22   ⋅   ⋅      ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  14   ⋅      ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  20      ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅      ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  …   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅     12   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅      ⋅  14   ⋅   ⋅   ⋅   ⋅

In [58]:
v = [1,2,3]
Diagonal(v) # if use vector as input, vector becomes diagonal

3×3 Diagonal{Int64, Vector{Int64}}:
 1  ⋅  ⋅
 ⋅  2  ⋅
 ⋅  ⋅  3

In [59]:
B = A[1:2, 3:4]

2×2 Matrix{Int64}:
 11  18
  7  11

In [60]:
C = A[1:2, 11:end] # end = call all the way to last column

2×10 Matrix{Int64}:
 13  12  11  15  12  13  14  14  12  12
  7   9   9   9   8  10  11  10   9   9

In [61]:
[B C] # bind two matrices by rows

2×12 Matrix{Int64}:
 11  18  13  12  11  15  12  13  14  14  12  12
  7  11   7   9   9   9   8  10  11  10   9   9

In [62]:
hcat(B, C) # function to bind two matrices horizontally

2×12 Matrix{Int64}:
 11  18  13  12  11  15  12  13  14  14  12  12
  7  11   7   9   9   9   8  10  11  10   9   9

In [63]:
# bind by columns

[
  A[1:2,:]
  A[11:end,:]
]

12×20 Matrix{Int64}:
 22  10  11  18  10  10  16   9  14  …  12  11  15  12  13  14  14  12  12
 10  12   7  11   8   6  12  10   9      9   9   9   8  10  11  10   9   9
 13   7   9   9   9   4  11   8   9      8   7   8  10   9   9   9   8  13
 12   9   6  13  10   6   9   6   8     12   9   8  10   9  10  10  10   8
 11   9   5  11   8   7  11   7   5      9  14  11   9   8  12   7   8   9
 15   9   8  13   4   9  15   9  10  …   8  11  17   9  11  12  10   8   8
 12   8   8  12  11   7  10   7   8     10   9   9  14  12   8   8   7  10
 13  10  11  14  10  10  14  11  12      9   8  11  12  17   9  10   7  10
 14  11   9  14   9   7  15  11  12     10  12  12   8   9  21  13  12  10
 14  10   9  14   7   6  12   9  12     10   7  10   8  10  13  15  12   8
 12   9   6  12   7   5  10   7   9  …  10   8   8   7   7  12  12  14   8
 12   9   9   8  11   5  14  11  10      8   9   8  10  10  10   8   8  17

In [64]:
# bind vertically

In [66]:
sort(M[:,1])

10-element Vector{Int64}:
 0
 1
 1
 1
 1
 1
 2
 2
 2
 2

In [70]:
index = sortperm(M[:,1])

10-element Vector{Int64}:
  2
  4
  6
  7
  8
  9
  1
  3
  5
 10

In [68]:
using SparseArrays, LinearAlgebra # need row index, column index, values

In [71]:
M[index,1]

10-element Vector{Int64}:
 0
 1
 1
 1
 1
 1
 2
 2
 2
 2

In [69]:
# create sparse matrix

sparse([1,2,2],[1,1,3],[9,10,11])

2×3 SparseMatrixCSC{Int64, Int64} with 3 stored entries:
  9  ⋅   ⋅
 10  ⋅  11

In [72]:
# sparse zero matrix

spzeros(2,2)

2×2 SparseMatrixCSC{Float64, Int64} with 0 stored entries:
  ⋅    ⋅ 
  ⋅    ⋅ 

In [73]:
# sparse identity matrix

N = 5
R = sparse(1.0I,N,N)

5×5 SparseMatrixCSC{Float64, Int64} with 5 stored entries:
 1.0   ⋅    ⋅    ⋅    ⋅ 
  ⋅   1.0   ⋅    ⋅    ⋅ 
  ⋅    ⋅   1.0   ⋅    ⋅ 
  ⋅    ⋅    ⋅   1.0   ⋅ 
  ⋅    ⋅    ⋅    ⋅   1.0

In [78]:
for i = 1:3
  @show i
end

i = 1
i = 2
i = 3


In [77]:
# for loop

result = zero(u)
for i=1:size(u,1)
    result[i] = u[i] + v[i]
end
[u v result]

LoadError: ignored

In [79]:
r = range(0, step = 0.1, stop = 1)

0.0:0.1:1.0

In [80]:
typeof(r)

StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}

In [81]:
r = 0:0.1:1

0.0:0.1:1.0

In [82]:
sin.(r) # sine; dot symbol '.' means element-wise operation

11-element Vector{Float64}:
 0.0
 0.09983341664682815
 0.19866933079506122
 0.29552020666133955
 0.3894183423086505
 0.479425538604203
 0.5646424733950354
 0.644217687237691
 0.7173560908995228
 0.7833269096274834
 0.8414709848078965

In [89]:
u

5-element Vector{Float64}:
 2.2
 2.2
 2.2
 2.2
 2.2

In [86]:
sum(u)

11.0

In [87]:
prod(u)

51.536320000000025

In [90]:
maximum(u)

2.2

In [91]:
minimum(u)

2.2

In [92]:
mean(u)

2.2

In [93]:
mode(u)

2.2

In [94]:
# type of M
typeof(M)

Matrix{Int64} (alias for Array{Int64, 2})

In [95]:
# type of v
typeof(v)

Vector{Int64} (alias for Array{Int64, 1})

In [97]:
# example of user-defined type

mutable struct BankAccount # mutable = can be changed
  accountNumber :: Int64
  firstName :: String
  lastName :: String
  balance :: Float64
end

In [98]:
fieldnames(BankAccount)

(:accountNumber, :firstName, :lastName, :balance)

In [99]:
# get types of all fields

BankAccount.types

svec(Int64, String, String, Float64)

In [100]:
a1 = BankAccount(1234, "Tom", "Smith", 1000.0)

BankAccount(1234, "Tom", "Smith", 1000.0)

In [101]:
a1.balance

1000.0

In [102]:
# can modify fields of mutable struct

a1.balance = 2000.50

2000.5

In [104]:
# dictionary --> key-value pairs

d = Dict{Int64,BankAccount}()

Dict{Int64, BankAccount}()

In [105]:
@show a1

a1 = BankAccount(1234, "Tom", "Smith", 2000.5)


BankAccount(1234, "Tom", "Smith", 2000.5)

In [106]:
d[a1.accountNumber] = a1 # add new key-value pair into dictionary: dict[value] = key
d

Dict{Int64, BankAccount} with 1 entry:
  1234 => BankAccount(1234, "Tom", "Smith", 2000.5)

In [114]:
function name_of_fcn(a;c=1) # use ';' and '=' to specify value for variable
  a + c
end

name_of_fcn (generic function with 3 methods)

In [115]:
name_of_fcn(2, c = 100)

102

In [116]:
function addVectors(u,v)
    if size(u,1) != size(v,1)
        println("The size of u (= $(size(u,1))) is not equal to the size of v (= $(size(v,1))) ")
        return []
    end
    result = zero(u)
    for i=1:size(u,1)
        result[i] = u[i] + v[i]
    end
    return result
end

addVectors (generic function with 1 method)

In [119]:
# 1.7 reading and writing from files

using Printf # needed for formatted print commands

In [120]:
A = randn(5,3)

5×3 Matrix{Float64}:
 -0.00128422   0.797386  -0.25063
 -0.455078    -0.780157  -0.160705
  0.0438358    2.25957   -0.270619
  0.0978471    1.07242   -0.209595
 -1.5255       0.402236   1.29503

In [131]:
out = open("outFile1.txt","w") # create an IO pathway to save/write printed values
n,p = size(A)
for j=1:p
    for i=1:n
        @printf(out,"%10.5f ", A[i,j]) # print A[i,j] in ten characters wide
    end
    @printf(out,"\n")
end
close(out)

In [132]:
;cat outFile1.txt

  -0.00128   -0.45508    0.04384    0.09785   -1.52550 
   0.79739   -0.78016    2.25957    1.07242    0.40224 
  -0.25063   -0.16071   -0.27062   -0.20959    1.29503 


In [138]:
out = open("outFile2.txt","w")
n,p = size(A)
for j=1:p
    for i=1:n
        print(out,A[i,j]," ")
    end
    print(out,"\n")
end
close(out)

In [139]:
;cat outFile2.txt

-0.0012842168187641057 -0.45507826523751904 0.04383579186329076 0.097847060132308 -1.5255039787302815 
0.7973857818300075 -0.78015698239879 2.259565254760825 1.0724195956491567 0.40223557414246686 
-0.25062983810260203 -0.16070527479335753 -0.2706190179832208 -0.209594841767682 1.295030109554738 


In [140]:
out = open("outFile3.txt","w")
n,p = size(A)
for j=1:p
    for i=1:n
        @printf(out,"%10.5e ", A[i,j])
    end
    @printf(out,"\n")
end
close(out)

In [141]:
;cat outFile3.txt

-1.28422e-03 -4.55078e-01 4.38358e-02 9.78471e-02 -1.52550e+00 
7.97386e-01 -7.80157e-01 2.25957e+00 1.07242e+00 4.02236e-01 
-2.50630e-01 -1.60705e-01 -2.70619e-01 -2.09595e-01 1.29503e+00 


In [142]:
inStream = open("outFile3.txt", "r") # read file
for line = eachline(inStream)
  println(line)
end
close(inStream)

-1.28422e-03 -4.55078e-01 4.38358e-02 9.78471e-02 -1.52550e+00 
7.97386e-01 -7.80157e-01 2.25957e+00 1.07242e+00 4.02236e-01 
-2.50630e-01 -1.60705e-01 -2.70619e-01 -2.09595e-01 1.29503e+00 


In [144]:
B = Array{Float64, 2}(undef,5,3)

5×3 Matrix{Float64}:
 0.0           0.0           0.0
 0.0           6.95145e-310  0.0
 0.0           0.0           0.0
 0.0           6.95142e-310  6.95146e-310
 6.95145e-310  0.0           0.0

In [145]:
B = zeros(5,3)

5×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [147]:
inStream = open("outFile","r")
j = 1
for line = eachline(inStream)
    println("input at line $j:")
    @show(line)
    @show(split(line))
    @show(parse.(Float64, split(line)))
    B[:,j] = parse.(Float64,split(line)) # split
    j += 1
end
close(inStream)

input at line 1:
line = "-1.28422e-03 -4.55078e-01 4.38358e-02 9.78471e-02 -1.52550e+00 "
split(line) = SubString{String}["-1.28422e-03", "-4.55078e-01", "4.38358e-02", "9.78471e-02", "-1.52550e+00"]
parse.(Float64, split(line)) = [-0.00128422, -0.455078, 0.0438358, 0.0978471, -1.5255]
input at line 2:
line = "7.97386e-01 -7.80157e-01 2.25957e+00 1.07242e+00 4.02236e-01 "
split(line) = SubString{String}["7.97386e-01", "-7.80157e-01", "2.25957e+00", "1.07242e+00", "4.02236e-01"]
parse.(Float64, split(line)) = [0.797386, -0.780157, 2.25957, 1.07242, 0.402236]
input at line 3:
line = "-2.50630e-01 -1.60705e-01 -2.70619e-01 -2.09595e-01 1.29503e+00 "
split(line) = SubString{String}["-2.50630e-01", "-1.60705e-01", "-2.70619e-01", "-2.09595e-01", "1.29503e+00"]
parse.(Float64, split(line)) = [-0.25063, -0.160705, -0.270619, -0.209595, 1.29503]


In [148]:
B

5×3 Matrix{Float64}:
 -0.00128422   0.797386  -0.25063
 -0.455078    -0.780157  -0.160705
  0.0438358    2.25957   -0.270619
  0.0978471    1.07242   -0.209595
 -1.5255       0.402236   1.29503

In [149]:
;cat outFile1.txt

  -0.00128   -0.45508    0.04384    0.09785   -1.52550 
   0.79739   -0.78016    2.25957    1.07242    0.40224 
  -0.25063   -0.16071   -0.27062   -0.20959    1.29503 


In [150]:
# 1.8 working with data frames

using DataFrames, CSV

In [151]:
mydf = DataFrame(ID=1:3, y=randn(3), m1=[0.0,1.0,2.0],m2=[2.0,2.0,1.0])

3×4 DataFrame
 Row │ ID     y           m1       m2      
     │ Int64  Float64     Float64  Float64 
─────┼─────────────────────────────────────
   1 │     1  -0.14198        0.0      2.0
   2 │     2   0.0369623      1.0      2.0
   3 │     3  -1.80024        2.0      1.0

In [152]:
# can create data frame from matrix
m = [0.0 2.0
     1.0 2.0
     2.0 1.0]
dfnames = ["m1", "m2"]
mydf = DataFrame(m, dfnames)

3×2 DataFrame
 Row │ m1       m2      
     │ Float64  Float64 
─────┼──────────────────
   1 │     0.0      2.0
   2 │     1.0      2.0
   3 │     2.0      1.0

In [153]:
insertcols!(mydf, 1, :ID => 1:3) #1 means the 1st column

3×3 DataFrame
 Row │ ID     m1       m2      
     │ Int64  Float64  Float64 
─────┼─────────────────────────
   1 │     1      0.0      2.0
   2 │     2      1.0      2.0
   3 │     3      2.0      1.0

In [154]:
insertcols!(mydf, 2, :y => randn(3)) #2 means the 2nd column

3×4 DataFrame
 Row │ ID     y          m1       m2      
     │ Int64  Float64    Float64  Float64 
─────┼────────────────────────────────────
   1 │     1  -0.26249       0.0      2.0
   2 │     2  -0.419363      1.0      2.0
   3 │     3  -0.688003      2.0      1.0

In [160]:
# change type of column
# '!' = all rows of the data frame (similar to ':' but sometimes used differently)
# ':<name>' --> <name> specifies which column (by column name)

mydf[!,:ID] = string.(mydf[!,:ID]) #change from Int64 to string

3-element Vector{String}:
 "1"
 "2"
 "3"

In [161]:
mydf

3×4 DataFrame
 Row │ ID      y          m1       m2      
     │ String  Float64    Float64  Float64 
─────┼─────────────────────────────────────
   1 │ 1       -0.26249       0.0      2.0
   2 │ 2       -0.419363      1.0      2.0
   3 │ 3       -0.688003      2.0      1.0

In [162]:
# save data frame as csv

CSV.write("test.csv", mydf)

"test.csv"

In [163]:
# read data from csv files as data frame

mydf=CSV.read("test.csv",DataFrame)
mydf[!,:ID] = string.(mydf[!,:ID]);
mydf

3×4 DataFrame
 Row │ ID      y          m1       m2      
     │ String  Float64    Float64  Float64 
─────┼─────────────────────────────────────
   1 │ 1       -0.26249       0.0      2.0
   2 │ 2       -0.419363      1.0      2.0
   3 │ 3       -0.688003      2.0      1.0

In [164]:
# access columns of data frame without copying

mydf[!,"ID"] # whole column # === mydf[!,:ID]

3-element Vector{String}:
 "1"
 "2"
 "3"

In [168]:
mydf[!,1:2] # == mydf[!,[:ID,:y]], mydf[!,["ID", "y"]]

3×2 DataFrame
 Row │ ID           y         
     │ String       Float64   
─────┼────────────────────────
   1 │ will change  -0.26249
   2 │ 2            -0.419363
   3 │ 3            -0.688003

In [169]:
mydf[!,[:ID,:y]]

3×2 DataFrame
 Row │ ID           y         
     │ String       Float64   
─────┼────────────────────────
   1 │ will change  -0.26249
   2 │ 2            -0.419363
   3 │ 3            -0.688003

In [172]:
a=mydf[!,"ID"]
a[1]="will change";
mydf # mydf's value will change as dataframe a changes, since a and mydf are just two names of the same object

3×4 DataFrame
 Row │ ID           y          m1       m2      
     │ String       Float64    Float64  Float64 
─────┼──────────────────────────────────────────
   1 │ will change  -0.26249       0.0      2.0
   2 │ 2            -0.419363      1.0      2.0
   3 │ 3            -0.688003      2.0      1.0

In [173]:
# get a copy of the column
# can use 'copy' function with '!' instead of just ':' to be less confusing

mydf[:,"ID"]

3-element Vector{String}:
 "will change"
 "2"
 "3"

In [174]:
a=mydf[:,"ID"]
a[1]="this won't change"; #will not change because a is the copy of the column
mydf

3×4 DataFrame
 Row │ ID           y          m1       m2      
     │ String       Float64    Float64  Float64 
─────┼──────────────────────────────────────────
   1 │ will change  -0.26249       0.0      2.0
   2 │ 2            -0.419363      1.0      2.0
   3 │ 3            -0.688003      2.0      1.0

In [175]:
mydf[:,:ID] = ["a1","a2","a3"]; #this will change the column
mydf

3×4 DataFrame
 Row │ ID      y          m1       m2      
     │ String  Float64    Float64  Float64 
─────┼─────────────────────────────────────
   1 │ a1      -0.26249       0.0      2.0
   2 │ a2      -0.419363      1.0      2.0
   3 │ a3      -0.688003      2.0      1.0

In [176]:
mydf[!,:ID] = ["ind1","ind2","ind3"]; #this will change the column
mydf

3×4 DataFrame
 Row │ ID      y          m1       m2      
     │ String  Float64    Float64  Float64 
─────┼─────────────────────────────────────
   1 │ ind1    -0.26249       0.0      2.0
   2 │ ind2    -0.419363      1.0      2.0
   3 │ ind3    -0.688003      2.0      1.0

In [177]:
# indexing

mydf[1:2, :y]

2-element Vector{Float64}:
 -0.2624901793293144
 -0.41936328311119286

In [178]:
mydf[1:2, [:y]]

2×1 DataFrame
 Row │ y         
     │ Float64   
─────┼───────────
   1 │ -0.26249
   2 │ -0.419363

In [181]:
mydf[1:2, [1,3]] # returns a data frame object

2×2 DataFrame
 Row │ ID      m1      
     │ String  Float64 
─────┼─────────────────
   1 │ ind1        0.0
   2 │ ind2        1.0

In [182]:
mydf[1:2, end] # end means the last column

2-element Vector{Float64}:
 2.0
 2.0

In [183]:
mydf[1:2, [end]] # get last column as data frame

2×1 DataFrame
 Row │ m2      
     │ Float64 
─────┼─────────
   1 │     2.0
   2 │     2.0

In [186]:
# data frame to matrix

Matrix(mydf[:,[:m1,:m2]]) # == Matrix(mydf[!,[:m1,:m2]])

3×2 Matrix{Float64}:
 0.0  2.0
 1.0  2.0
 2.0  1.0

In [185]:
# get basic information about data frame

size(mydf)

(3, 4)

In [187]:
size(mydf, 1) # number of rows (also works for matrix)

3

In [188]:
size(mydf, 2) # number of columns (also works for matrix)

4

In [189]:
nrow(mydf) # only works for data frame

3

In [190]:
ncol(mydf) # only works for data frame

4

In [191]:
first(mydf, 2) # show the first 2 rows of dataframe

2×4 DataFrame
 Row │ ID      y          m1       m2      
     │ String  Float64    Float64  Float64 
─────┼─────────────────────────────────────
   1 │ ind1    -0.26249       0.0      2.0
   2 │ ind2    -0.419363      1.0      2.0

In [192]:
last(mydf, 3) # show the last 3 rows of data frame

3×4 DataFrame
 Row │ ID      y          m1       m2      
     │ String  Float64    Float64  Float64 
─────┼─────────────────────────────────────
   1 │ ind1    -0.26249       0.0      2.0
   2 │ ind2    -0.419363      1.0      2.0
   3 │ ind3    -0.688003      2.0      1.0

In [194]:
first(Matrix(mydf), 2) # show the first 2 elements of data frame

2-element Vector{Any}:
 "ind1"
 "ind2"

In [195]:
last(Matrix(mydf), 4) # show the last 4 elements of data frame

4-element Vector{Any}:
 2.0
 2.0
 2.0
 1.0