In [ ]:
%%shell
set -e

#---------------------------------------------------#
JULIA_VERSION="1.7.1" # any version ≥ 0.7.0
JULIA_PACKAGES="IJulia CSV DataFrames Random Statistics Distributions LinearAlgebra SparseArrays Printf JWAS"  # CSV DataFrames Random Statistics JWAS Distributions LinearAlgebra
JULIA_PACKAGES_IF_GPU=""
JULIA_NUM_THREADS=4
#---------------------------------------------------#

if [ -n "$COLAB_GPU" ] && [ -z `which julia` ]; then
  # Install Julia
  JULIA_VER=`cut -d '.' -f -2 <<< "$JULIA_VERSION"`
  echo "Installing Julia $JULIA_VERSION on the current Colab Runtime..."
  BASE_URL="https://julialang-s3.julialang.org/bin/linux/x64"
  URL="$BASE_URL/$JULIA_VER/julia-$JULIA_VERSION-linux-x86_64.tar.gz"
  wget -nv $URL -O /tmp/julia.tar.gz # -nv means "not verbose"
  tar -x -f /tmp/julia.tar.gz -C /usr/local --strip-components 1
  rm /tmp/julia.tar.gz

  # Install Packages
  if [ "$COLAB_GPU" = "1" ]; then
      JULIA_PACKAGES="$JULIA_PACKAGES $JULIA_PACKAGES_IF_GPU"
  fi
  for PKG in `echo $JULIA_PACKAGES`; do
    echo "Installing Julia package $PKG..."
    julia -e 'using Pkg; pkg"add '$PKG'; precompile;"' &> /dev/null
  done

  # Install kernel and rename it to "julia"
  echo "Installing IJulia kernel..."
  julia -e 'using IJulia; IJulia.installkernel("julia", env=Dict(
      "JULIA_NUM_THREADS"=>"'"$JULIA_NUM_THREADS"'"))'
  KERNEL_DIR=`julia -e "using IJulia; print(IJulia.kerneldir())"`
  KERNEL_NAME=`ls -d "$KERNEL_DIR"/julia*`
  mv -f $KERNEL_NAME "$KERNEL_DIR"/julia  

  echo ''
  echo "Successfully installed `julia -v`!"
  echo "Please reload this page (press Ctrl+R, ⌘+R, or the F5 key) then"
  echo "jump to the 'Checking the Installation' section."
fi

Installing Julia 1.7.1 on the current Colab Runtime...
2022-08-01 04:12:08 URL:https://storage.googleapis.com/julialang2/bin/linux/x64/1.7/julia-1.7.1-linux-x86_64.tar.gz [123374573/123374573] -> "/tmp/julia.tar.gz" [1]
Installing Julia package IJulia...
Installing Julia package CSV...
Installing Julia package DataFrames...
Installing Julia package Random...
Installing Julia package Statistics...
Installing Julia package JWAS...
Installing IJulia kernel...
[ Info: Installing julia kernelspec in /root/.local/share/jupyter/kernels/julia-1.7

Please reload this page (press Ctrl+R, ⌘+R, or the F5 key) then
jump to the 'Checking the Installation' section.


In [1]:
versioninfo()

Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_NUM_THREADS = 4


In [10]:
a = 2.5

2.5

In [11]:
5a

12.5

In [7]:
5*a

12.5

In [8]:
ans

In [13]:
a,b = 1,2

(1, 2)

In [14]:
[a,b]

2-element Vector{Int64}:
 1
 2

In [15]:
a,b = b,a
[a,b]

2-element Vector{Int64}:
 2
 1

In [16]:
1 < a < 3

true

In [17]:
1 < a && a < 3

true

In [18]:
# ternary operator
# res = new variable
# if a == b, then res = a, else res = b
# in this case a == b, so res = a (res = 1)

a = 1
b = 1
c = 2

res = a==b ? a : b

1

In [19]:
# if a == c, then print out a, otherwise print out c
# in this case, a =/= c, so print out c (2)

a == c ? a : c

2

In [20]:
a == c ? 1 : 10

10

In [21]:
a == c-b ? 1 : 10

1

In [22]:
# remainder

99 % 10

9

Arrays

In [23]:
# declaration, initialization, and indexing

# empty vector of double precision floats
# floats = includes decimals
# 64 = take up different computer memory space, different ammount of precision (can be 16, 32, 64 --> larger num = higher precision)
# 1 = array dimension of 1 (vector)
v = Array{Float64,1}()

Float64[]

In [24]:
push!(v,2.0) # push number to vector v

1-element Vector{Float64}:
 2.0

In [25]:
v

1-element Vector{Float64}:
 2.0

In [27]:
push!(v, 3.6)

2-element Vector{Float64}:
 2.0
 3.6

In [34]:
# create vector of size 5

u = Array{Float64,1}(undef, 5) # undef = randomly generated numbers (doesn't matter what the values are, just want to create vector)

5-element Vector{Float64}:
   5.0e-324
   1.0e-323
 NaN
 NaN
   6.9523669473396e-310

In [35]:
# create matrix of size 3x5
# double precision = way to store values, 64 bits to store
# single precision = 32 bits to store

U = Array{Float64, 2}(undef, 3, 5)

3×5 Matrix{Float64}:
 6.95234e-310  6.95234e-310  6.95234e-310  6.95234e-310  6.95234e-310
 6.95234e-310  6.95234e-310  6.95234e-310  6.95234e-310  6.95234e-310
 6.95234e-310  6.95234e-310  6.95234e-310  6.95234e-310  3.5e-323

In [36]:
# vector of size 5, of 2.2

u = fill(2.2, 5)

5-element Vector{Float64}:
 2.2
 2.2
 2.2
 2.2
 2.2

In [37]:
# vector with 5 zeros

zeros(5)

5-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [38]:
zeros(3,5)

3×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [39]:
# create zero matrix (same size as U)

zero(U)

3×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [40]:
U

3×5 Matrix{Float64}:
 6.95234e-310  6.95234e-310  6.95234e-310  6.95234e-310  6.95234e-310
 6.95234e-310  6.95234e-310  6.95234e-310  6.95234e-310  6.95234e-310
 6.95234e-310  6.95234e-310  6.95234e-310  6.95234e-310  3.5e-323

In [41]:
ones(3,5)

3×5 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [46]:
using Random, Statistics, Distributions, LinearAlgebra, DataFrames

In [45]:
# another way to install packages if run into error

#using Pkg
#Pkg.add("Distributions")

In [58]:
Random.seed!(101)

TaskLocalRNG()

In [59]:
rand(3,5) # uniform(0,1) --> uniform distribution from 0 to 1

3×5 Matrix{Float64}:
 0.467922  0.822268   0.311185  0.127011  0.305472
 0.304417  0.0189185  0.759787  0.227176  0.385999
 0.238407  0.446988   0.56523   0.253949  0.246393

In [60]:
randn(3,5) # standard normal

3×5 Matrix{Float64}:
 -2.78713   0.697746   0.193796  0.958825  -1.87977
  1.02219   0.909278   1.43393   0.582366  -0.496949
 -0.187686  1.58094   -0.64995   1.55612    0.92985

In [61]:
mean(randn(1_000_000)) # '_' == ',' (1_000_000 == 1,000,000)

-0.0007975530088560181

In [62]:
var(randn(1_000_000))

1.0014996619665901

In [80]:
Random.seed!(100)

TaskLocalRNG()

In [81]:
M = rand(Binomial(2,0.5),10,20)

10×20 Matrix{Int64}:
 2  1  0  2  0  1  1  0  0  0  0  1  2  2  0  0  2  1  1  0
 0  1  0  0  2  0  1  1  0  1  1  1  2  0  1  0  2  0  1  2
 2  0  1  0  0  0  2  1  2  1  2  0  0  1  0  0  1  1  1  2
 1  1  2  1  0  1  2  2  1  1  1  0  1  2  1  2  2  1  0  1
 2  0  1  2  2  2  1  0  1  2  1  1  1  1  2  2  0  0  0  1
 1  2  1  1  1  1  2  2  1  1  1  1  1  1  1  2  0  1  1  2
 1  1  0  1  0  1  2  1  2  1  0  1  1  2  1  1  1  1  1  0
 1  1  1  2  1  1  1  1  2  0  0  1  0  0  0  1  2  2  2  0
 1  1  1  1  2  0  1  1  2  1  1  1  0  0  1  1  1  1  0  1
 2  1  1  2  1  0  0  0  0  1  2  2  1  1  2  1  1  2  2  1

In [82]:
# [row, column]

M[:,1]

10-element Vector{Int64}:
 2
 0
 2
 1
 2
 1
 1
 1
 1
 2

In [83]:
M[1,:]

20-element Vector{Int64}:
 2
 1
 0
 2
 0
 1
 1
 0
 0
 0
 0
 1
 2
 2
 0
 0
 2
 1
 1
 0

In [84]:
# transposing

M[1,:]'

1×20 adjoint(::Vector{Int64}) with eltype Int64:
 2  1  0  2  0  1  1  0  0  0  0  1  2  2  0  0  2  1  1  0

In [85]:
M[1,:]'M[1,:]

26

In [86]:
M[1,:]'*M[1,:]

26

In [87]:
# dot product (matrix multiplication)

dot(M[1,:],M[1,:])

26

In [88]:
# calcualte dot product manually (square every element and then add)
# '.' = do operation on every element in matrix

M[1,:].^2

20-element Vector{Int64}:
 4
 1
 0
 4
 0
 1
 1
 0
 0
 0
 0
 1
 4
 4
 0
 0
 4
 1
 1
 0

In [89]:
sum(M[1,:].^2)

26

In [90]:
M'M == M'*M

true

In [91]:
# identity matrix

I(3)

3×3 Diagonal{Bool, Vector{Bool}}:
 1  ⋅  ⋅
 ⋅  1  ⋅
 ⋅  ⋅  1

In [93]:
1I(3)

3×3 Diagonal{Int64, Vector{Int64}}:
 1  ⋅  ⋅
 ⋅  1  ⋅
 ⋅  ⋅  1

In [94]:
1.0I(2)

2×2 Diagonal{Float64, Vector{Float64}}:
 1.0   ⋅ 
  ⋅   1.0

In [95]:
A = M'M + I # don't need to specify dimensions for I (will infer same dimension)

20×20 Matrix{Int64}:
 22  10  11  18  10  10  16   9  14  …  12  11  15  12  13  14  14  12  12
 10  12   7  11   8   6  12  10   9      9   9   9   8  10  11  10   9   9
 11   7  11  10   7   6  11   9  10      6   5   8   8  11   9   9   6   9
 18  11  10  21  11  11  13   8  12     13  11  13  12  14  14  14  12   8
 10   8   7  11  16   6   9   7   9     10   8   4  11  10   9   7   7  11
 10   6   6  11   6  10  10   6   8  …   6   7   9   7  10   7   6   5   5
 16  12  11  13   9  10  22  15  17      9  11  15  10  14  15  12  10  14
  9  10   9   8   7   6  15  14  12      6   7   9   7  11  11   9   7  11
 14   9  10  12   9   8  17  12  20      8   5  10   8  12  12  12   9  10
 12   7   8  10  10   7  12   8  10      8   8   9  11  11   8   7   6  11
 13   7   9   9   9   4  11   8   9  …   8   7   8  10   9   9   9   8  13
 12   9   6  13  10   6   9   6   8     12   9   8  10   9  10  10  10   8
 11   9   5  11   8   7  11   7   5      9  14  11   9   8  12   7   8   9
 15 

In [96]:
M'M + I(20) # can specify dimensions for I but don't need to

20×20 Matrix{Int64}:
 22  10  11  18  10  10  16   9  14  …  12  11  15  12  13  14  14  12  12
 10  12   7  11   8   6  12  10   9      9   9   9   8  10  11  10   9   9
 11   7  11  10   7   6  11   9  10      6   5   8   8  11   9   9   6   9
 18  11  10  21  11  11  13   8  12     13  11  13  12  14  14  14  12   8
 10   8   7  11  16   6   9   7   9     10   8   4  11  10   9   7   7  11
 10   6   6  11   6  10  10   6   8  …   6   7   9   7  10   7   6   5   5
 16  12  11  13   9  10  22  15  17      9  11  15  10  14  15  12  10  14
  9  10   9   8   7   6  15  14  12      6   7   9   7  11  11   9   7  11
 14   9  10  12   9   8  17  12  20      8   5  10   8  12  12  12   9  10
 12   7   8  10  10   7  12   8  10      8   8   9  11  11   8   7   6  11
 13   7   9   9   9   4  11   8   9  …   8   7   8  10   9   9   9   8  13
 12   9   6  13  10   6   9   6   8     12   9   8  10   9  10  10  10   8
 11   9   5  11   8   7  11   7   5      9  14  11   9   8  12   7   8   9
 15 

In [97]:
B = rand(3,3) + I

3×3 Matrix{Float64}:
 1.45742     0.905428  0.428537
 0.00450378  1.4083    0.831837
 0.26018     0.940167  1.68669

In [98]:
B*I

3×3 Matrix{Float64}:
 1.45742     0.905428  0.428537
 0.00450378  1.4083    0.831837
 0.26018     0.940167  1.68669

In [99]:
B == B*I

true

In [100]:
B === B*I # triple equality = whether two operations are exactly the same (even if values are the same)

false

In [101]:
Diagonal(A) # all diagonal values of matrix

20×20 Diagonal{Int64, Vector{Int64}}:
 22   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  …   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅  12   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅      ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅  11   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅      ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅  21   ⋅   ⋅   ⋅   ⋅   ⋅      ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅   ⋅  16   ⋅   ⋅   ⋅   ⋅      ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅  10   ⋅   ⋅   ⋅  …   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  22   ⋅   ⋅      ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  14   ⋅      ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  20      ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅      ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅  …   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅     12   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅
  ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅   ⋅      ⋅  14   ⋅   ⋅   ⋅   ⋅

In [102]:
v = [1,2,3]
Diagonal(v) # if use vector as input, vector becomes diagonal

3×3 Diagonal{Int64, Vector{Int64}}:
 1  ⋅  ⋅
 ⋅  2  ⋅
 ⋅  ⋅  3

In [104]:
B = A[1:2, 3:4]

2×2 Matrix{Int64}:
 11  18
  7  11

In [105]:
C = A[1:2, 11:end] # end = call all the way to last column

2×10 Matrix{Int64}:
 13  12  11  15  12  13  14  14  12  12
  7   9   9   9   8  10  11  10   9   9

In [106]:
[B C] # bind two matrices by rows

2×12 Matrix{Int64}:
 11  18  13  12  11  15  12  13  14  14  12  12
  7  11   7   9   9   9   8  10  11  10   9   9

In [108]:
hcat(B, C) # function to bind two matrices horizontally

2×12 Matrix{Int64}:
 11  18  13  12  11  15  12  13  14  14  12  12
  7  11   7   9   9   9   8  10  11  10   9   9

In [109]:
# bind by columns

[
  A[1:2,:]
  A[11:end,:]
]

12×20 Matrix{Int64}:
 22  10  11  18  10  10  16   9  14  …  12  11  15  12  13  14  14  12  12
 10  12   7  11   8   6  12  10   9      9   9   9   8  10  11  10   9   9
 13   7   9   9   9   4  11   8   9      8   7   8  10   9   9   9   8  13
 12   9   6  13  10   6   9   6   8     12   9   8  10   9  10  10  10   8
 11   9   5  11   8   7  11   7   5      9  14  11   9   8  12   7   8   9
 15   9   8  13   4   9  15   9  10  …   8  11  17   9  11  12  10   8   8
 12   8   8  12  11   7  10   7   8     10   9   9  14  12   8   8   7  10
 13  10  11  14  10  10  14  11  12      9   8  11  12  17   9  10   7  10
 14  11   9  14   9   7  15  11  12     10  12  12   8   9  21  13  12  10
 14  10   9  14   7   6  12   9  12     10   7  10   8  10  13  15  12   8
 12   9   6  12   7   5  10   7   9  …  10   8   8   7   7  12  12  14   8
 12   9   9   8  11   5  14  11  10      8   9   8  10  10  10   8   8  17

In [ ]:
# bind vertically